def show_git_commands():
    print("=== Popular Git Commands ===")
    print("")
    print("🔹 git init")
    print("  → Initializes a new Git repository in the current folder")
    print("")
    print("🔹 git status")
    print("  → Shows the current status of staged and unstaged changes")
    print("")
    print("🔹 git add <file>")
    print("  → Stages a file for commit")
    print("")
    print("🔹 git commit -m 'message'")
    print("  → Creates a new commit with the provided message")
    print("")
    print("🔹 git log")
    print("  → Displays the commit history")
    print("")
    print("🔹 git diff")
    print("  → Shows the changes not yet staged")
    print("")
    print("🔹 git branch")
    print("  → Lists all branches")
    print("")
    print("🔹 git checkout <branch>")
    print("  → Switches to the specified branch")
    print("")
    print("🔹 git push")
    print("  → Uploads local commits to the remote repository")
    print("")
    print("🔹 git pull")
    print("  → Fetches and merges changes from the remote repository")
    print("")
    print("==============================")
