def show_gcm_help():
    print("=== GCM Tool Instructions ===")
    print("")
    print("🔹 gcm")
    print("  → Automatically analyzes staged changes and generates a commit message")
    print("")
    print("🔹 gcm -config")
    print("  → Launches the configuration menu to set default commit style, auto-commit, and preview options")
    print("")
    print("🔹 gcm -a")
    print("  → Opens the advanced menu with development tools like commit tree, file diffs, and more")
    print("")
    print("=== Configuration Options ===")
    print("- default_style: commit message style (conventional | corporate | fun)")
    print("- auto_commit: automatically commit after generating the message (true/false)")
    print("- visual_preview: format for previewing the commit (default | markdown | minimal | boxed)")
    print("")
    print("=== Notes ===")
    print("- GCM uses the staged changes (git add) for analysis")
    print("- All settings are saved in ~/.gcmconfig")
    print("- Tool is fully local and offline")
    print("==============================")