#!/usr/bin/env python3
import sys
import os

def main():
    if len(sys.argv) < 2:
        print("Usage: gcm -config | -a")
        return

    arg = sys.argv[1]

    if arg == "-config":
        from config.config_generator import launch_config_menu
        launch_config_menu()
    elif arg == "-a":
        from core.instructions import launch_instruction_menu
        launch_instruction_menu()
    else:
        print("Unknown argument. Use -config or -a.")

if __name__ == "__main__":
    main()
